config/routes.rb
DanielkeetonCom::Application.routes.draw do

  root to: 'home#index'

  devise_for :admins, skip: :registrations

  resources :listings, only: [:show] do
    collection do
      get '/', to: 'listings#index', defaults: { status: 'for_sale' }
      get 'status/:status', to: 'listings#index', as: :status
    end
  end

  get '/homeworth', to: 'home#homeworth'

  resources :posts, only: [:index, :show]
  resources :inquiries, only: [:create]
  resources :pages, only: [:show]
  resources :testimonials, only: [:index]
  resources :vendors, only: [:index]
  resources :selling, only: [:index]

  namespace :admin do

    root to: 'listings#index'

    resources :listings, except: [:show]

    resources :posts, except: [:show]

    resources :pages, except: [:show]

    resources :testimonials, except: [:show]

    resources :vendors, except: [:show]

    resources :dynamic_contents, except: [:show]
  end

end

app/views/admin/pages/_form.haml
= form_for [:admin, page], html: { class: 'custom page-form' } do |f|
  .row
    .large-12.columns
      = f.label :title
      = f.text_field :title

  .row
    .large-12.columns
      = f.label :body
      = f.text_area :body

  %footer
    .row
      .large-6.columns
        = link_to 'Cancel', admin_pages_path, class: 'button secondary'
      .large-6.columns.text-right
        = f.submit 'Save', class: 'button success'

app/views/admin/pages/_pages.haml
- pages_header ||= 'Published Pages'
- include_new = true if include_new.nil?

%h4
  = pages_header
  - if include_new
    %span
      = link_to 'New', new_admin_page_path, class: 'button tiny'

%section
  %ul.admin-list
    - pages.each do |page|
      %li.row
        .large-10.columns
          = truncate(page.title, length: 75)
        .large-2.columns
          %ul.actions
            %li= link_to '', edit_admin_page_path(page), class: 'icon-edit'
            %li= link_to '', admin_page_path(page), method: :delete, confirm: 'Are you sure?', class: 'icon-delete'

app/views/admin/pages/edit.haml
%h4 Edit Page
%section
  = render 'form', page: @page

app/views/admin/pages/index.haml
= render 'pages', pages: @pages, pages_header: 'Pages'

app/views/admin/pages/new.haml
%h4 New Page
%section
  = render 'form', page: @page