config/routes.rb
DanielkeetonCom::Application.routes.draw do

  root to: 'home#index'

  devise_for :admins, skip: :registrations

  resources :listings, only: [:show] do
    collection do
      get '/', to: 'listings#index', defaults: { status: 'for_sale' }
      get 'status/:status', to: 'listings#index', as: :status
    end
  end

  get '/homeworth', to: 'home#homeworth'

  resources :posts, only: [:index, :show]
  resources :inquiries, only: [:create]
  resources :pages, only: [:show]
  resources :testimonials, only: [:index]
  resources :vendors, only: [:index]
  resources :selling, only: [:index]

  namespace :admin do

    root to: 'listings#index'

    resources :listings, except: [:show]

    resources :posts, except: [:show]

    resources :pages, except: [:show]

    resources :testimonials, except: [:show]

    resources :vendors, except: [:show]

    resources :dynamic_contents, except: [:show]
  end

end

app/models/listing.rb
# Public: The Listing class handles the storage of real estate listings in the
# website.
class Listing < ActiveRecord::Base

  # Internal: Valid states for a Listing.
  VALID_STATES = %w(for_sale for_rent under_contract sold cancelled)

  # Internal: Extend the FriendlyId module to allow us to use friendly_id.
  extend FriendlyId

  # Internal: Slug the :title of Listings using FriendlyId.
  friendly_id :title, use: [:slugged, :finders]

  # Internal: Each Listing has many Images.
  has_many :images, dependent: :destroy

  # Internal: Allow us to create Images from the Listing forms.
  accepts_nested_attributes_for :images, allow_destroy: true

  # Internal: Validate that at least one Image is stored with a Listing.
  validates :images, length: { minimum: 1 }

  # Internal: Use Geocoder to store latitude and longitude.
  geocoded_by :full_address

  # Internal: Validate presence of specific attributes.
  validates :title, :description, :price, presence: true

  # Internal: Validate presence and valid state of :status.
  validates :status, presence: true, inclusion: { in: Listing::VALID_STATES }

  # Internal: Validate presence and correct numericality of :bathrooms.
  validates :bathrooms, presence: true,
                        numericality: { greater_than_or_equal_to: 0 }

  # Internal: Validate presence and correct numericality of :bedrooms.
  validates :bedrooms, presence: true,
                        numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Internal: Validate numericality of :year_built, allow it to be nil.
  validates :year_built, numericality: { greater_than_or_equal_to: 1800 },
                          allow_nil: true

  # Internal: Validate numericality of :square_footage, allow it to be nil.
  validates :square_footage, numericality: { greater_than_or_equal_to: 500 },
                              allow_nil: true

  # Internal: Validate numericality of :lot_size, allow it to be nil.
  validates :lot_size, numericality: { greater_than_or_equal_to: 1000 },
                        allow_nil: true

  # Internal: Ensure that only one Listing is featured.
  before_save :ensure_single_featured

  # Internal: After validating the Listing, geocode for latitude and longitude.
  after_validation :geocode

  # Internal: The default scope should order by :status, then :id.
  default_scope { order(:status, :id) }

  # Public: Get all Listings where featured is set to true.
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :featured, -> { where(featured: true) }

  # Public: Get all Listings where status is set to 'for_sale.'
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :for_sale, -> { where(status: 'for_sale') }

  # Public: Get all Listings where status is set to 'for_rent.'
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :for_rent, -> { where(status: 'for_rent') }

  # Public: Get all Listings where status is set to 'under_contract.'
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :under_contract, -> { where(status: 'under_contract') }

  # Public: Get all Listings where status is set to 'sold.'
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :sold, -> { where(status: 'sold') }

  # Public: Get all Listings where status is set to 'cancelled.'
  #
  # Returns a Listing::FriendlyIdActiveRecordRelation.
  scope :cancelled, -> { where(status: 'cancelled') }

  # Public: Get a formatted version of my address.
  #
  # Returns a String.
  def full_address
    "#{address_line_1}, #{city}, #{state}, #{zip}"
  end

  # Public: Get the Image for the Listing with :primary set to true.
  #
  # Returns an Image.
  def primary_image
    self.images.primary.first
  end

private

  # Internal: Ensure that only one Listing is featured. If the current Listing
  # is not featured, this is basically a noop. If the current Listing is
  # featured, we update all other Listings to not be featured.
  #
  # Returns nothing.
  def ensure_single_featured
    Listing.all.delete_if { |l| l == self }.each do |listing|
      listing.update_column(:featured, false)
    end if self.featured
  end
end

app/controllers/admin/listings_controller.rb
class Admin::ListingsController < Admin::BaseController

  # Internal: A testable class for use with strong_parameters.
  class ListingParams

    # Internal: Build params for creating/updating a Listing.
    #
    # Examples
    #
    #   ListingParams.build(listing: { title: 'A Title' })
    #   # => { 'title' => 'A Title' }
    def self.build(params)
      params.require(:listing).permit!
    end
  end

  def index
    @listings = Listing.all.group_by(&:status)
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(ListingParams.build(params))
      redirect_to admin_listings_path, notice: 'Listing successfully updated!'
    else
      flash.now[:error] = 'Oops! There was a problem updating the listing.'
      render :edit
    end
  end

  def new
    @listing = Listing.new
    @listing.status = params[:status] unless params[:status].blank?
  end

  def create
    @listing = Listing.new(ListingParams.build(params))

    if @listing.save
      redirect_to admin_listings_path, notice: 'Listing successfully created!'
    else
      flash.now[:error] = 'Oops! There was a problem creating the listing.'
      render :new
    end
  end

  def destroy
    if Listing.find(params[:id]).destroy
      flash[:notice] = 'Listing successfully deleted!'
    else
      flash[:error] = 'Oops! There was a problem deleting the listing.'
    end

    redirect_to admin_listings_path
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @status = params[:status]

    unless Listing::VALID_STATES.include? @status
      render_404 and return
    end

    @listings = Listing.send(@status)
  end

  def show
    @listing = Listing.find(params[:id])
  end

end

app/helpers/listings_helper.rb
# Public: All helpers that are to be used for Listings are in here. Even though
# all helpers are application-wide, it makes sense to put them here for clarity.
module ListingsHelper

  # Public: Get the URL for a link to google maps with the address of a Listing.
  #
  # listing - The Listing to get the link for.
  #
  # Returns a String.
  def google_maps_address(listing)
    "http://maps.google.com/?q=#{listing.address_line_1}, #{listing.city}, #{listing.state}, #{listing.zip}"
  end

  # Public: Get the address of a Listing formatted for HTML.
  #
  # listing   - The Listing to format the address of.
  # opts      - The Hash of options to modify the result (default: {}).
  #             :p_class - The class to put on each paragraph tag.
  #
  # Returns an ActiveSupport::SafeBuffer.
  def pretty_address(listing, opts={})
    p_class = opts[:p_class] || "margin-bottom-5"

    content_tag(:div, class: "address") do
      root = []
      root << content_tag(:p, listing.address_line_1, class: p_class)
      root << content_tag(:p, listing.address_line_2, class: p_class) unless listing.address_line_2.nil?
      root << content_tag(:p, class: p_class) do
        elems = []
        elems << content_tag(:span, listing.city)
        elems << content_tag(:span, " #{listing.state}, ")
        elems << content_tag(:span, listing.zip)
        raw elems.join
      end
      raw root.join
    end
  end

  # Public: Get the subnav for Listing states. It will give us a definition list
  # using the foundation class 'sub-nav' and links to each visible state of
  # Listings in the site: for_sale, for_rent, under_contract, and sold.
  #
  # curr - The current state that we are looking at.
  #
  # Returns an ActiveSupport::SafeBuffer.
  def listing_status_nav(curr)
    curr = 'for_sale' if curr.blank?

    items = [
      content_tag(:dt, 'View listings that are:'),
      content_tag(:dd, link_to('For Sale', listings_path), class: curr == 'for_sale' ? 'active' : ''),
      content_tag(:dd, link_to('For Rent', status_listings_path('for_rent')), class: curr == 'for_rent' ? 'active' : ''),
      content_tag(:dd, link_to('Under Contract', status_listings_path('under_contract')), class: curr == 'under_contract' ? 'active' : ''),
      content_tag(:dd, link_to('Sold', status_listings_path('sold')), class: curr == 'sold' ? 'active' : '')
    ]

    content_tag :dl, class: 'sub-nav listings' do
      items.map do |item|
        concat(item)
      end
    end
  end


  # Public: Get the gallery of thumbnails for all Images of a Listing. Each link
  # has a class of 'fancybox' and a rel of 'gallery' so we can use fancybox to
  # create a gallery for the Images.
  #
  # listing - The Listing to get an unordered list of image thumbnails.
  #
  # Returns an ActiveSupport::SafeBuffer.
  def listing_gallery_thumbs(listing)
    return nil if listing.images.size <= 1
    items = []

    listing.images.each do |image|
      next if image.primary?
      items << link_to(image_tag(image.file.thumb), image.file.url,
                        class: 'fancybox', rel: 'gallery')
    end

    content_tag :ul, class: 'thumbnails' do
      items.map do |item|
        concat(content_tag(:li, item))
      end
    end
  end

  # Public: Get an Array of regions for local listings. I am not sure if these
  # are guaranteed to remain unchanged, so I will need to check into that.
  #
  # Returns an Array of Hashes.
  def local_listing_options
    regions = Region.order(:name).map { |r| [r.name, r.idx_value] }

    unless session[:region].blank?
      selected_region = regions.select { |r| r[0].downcase == session[:region] }
      selected_region = selected_region.first[1] unless selected_region.empty?
    end

    options_for_select(regions, selected_region)
  end

end

app/views/admin/listings/_form.haml
= nested_form_for [:admin, listing], html: { class: 'custom listing-form' } do |f|
  .row
    .large-12.columns
      = f.label :title
      = f.text_field :title

  .row
    .large-12.columns
      = f.label :description
      = f.text_area :description

  .row
    .large-6.columns
      = f.label :price
      = f.text_field :price
    .large-6.columns
      = f.label :status
      = f.select :status, Listing::VALID_STATES.each.map { |val| [val.titleize, val] }

  %hr.full-bleed

  .row
    .large-2.columns
      = f.label :bedrooms
      = f.select :bedrooms, (0..10)
    .large-2.columns
      = f.label :bathrooms
      = f.select :bathrooms, [0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    .large-2.columns
      = f.label :year_built, 'Year Built'
      = f.select :year_built, (1800..2013)
    .large-3.columns
      = f.label :square_footage, 'Square Feet'
      = f.text_field :square_footage
    .large-3.columns
      = f.label :lot_size, 'Lot Size (ft)'
      = f.text_field :lot_size

  %hr.full-bleed

  .row
    .large-6.columns
      = f.label :address_line_1
      = f.text_field :address_line_1
    .large-6.columns
      = f.label :address_line_2
      = f.text_field :address_line_2
  .row
    .large-4.columns
      = f.label :city
      = f.text_field :city
    .large-4.columns
      = f.label :state
      = f.text_field :state
    .large-4.columns
      = f.label :zip
      = f.text_field :zip

  %hr.full-bleed

  .images
    .image-fields
      - f.object.images.build if f.object.images.empty?
      = f.fields_for :images do |image_fields|
        .row
          - unless image_fields.object.file.blank?
            .large-2.columns
              = image_tag image_fields.object.file.thumb
          .large-1.columns
            = image_fields.label :file
          .large-5.columns
            = image_fields.file_field :file
          .large-4.columns.text-right
            = image_fields.link_to_remove 'Remove'

    = f.link_to_add 'Add an Image', :images, data: { target: '.image-fields' }


  %footer
    .row
      .large-6.columns
        = link_to 'Cancel', admin_listings_path, class: 'button secondary'
      .large-6.columns.text-right
        = f.submit 'Save', class: 'button success'

app/views/admin/listings/_listings.haml
%h4
  = status.titleize
  %span
    = link_to 'New', new_admin_listing_path(status: status), class: 'button tiny'
%section
  %ul.admin-list
    - listings.each do |listing|
      %li.row
        .large-10.columns
          %small.tag{class: listing.status}= listing.status.titleize.upcase
          = truncate(listing.title, length: 75)
        .large-2.columns
          %ul.actions
            %li= link_to '', edit_admin_listing_path(listing), class: 'icon-edit'
            %li= link_to '', admin_listing_path(listing), method: :delete, confirm: 'Are you sure?', class: 'icon-delete'

app/views/admin/listings/edit.haml
%h4 Edit Listing
%section
  = render 'form', listing: @listing

app/views/admin/listings/index.haml
- @listings.each do |status, listings|
  = render 'listings', status: status, listings: listings

app/views/admin/listings/new.haml
%h4 New Listing
%section
  = render 'form', listing: @listing