config/routes.rb
DanielkeetonCom::Application.routes.draw do

  root to: 'home#index'

  devise_for :admins, skip: :registrations

  resources :listings, only: [:show] do
    collection do
      get '/', to: 'listings#index', defaults: { status: 'for_sale' }
      get 'status/:status', to: 'listings#index', as: :status
    end
  end

  get '/homeworth', to: 'home#homeworth'

  resources :posts, only: [:index, :show]
  resources :inquiries, only: [:create]
  resources :pages, only: [:show]
  resources :testimonials, only: [:index]
  resources :vendors, only: [:index]
  resources :selling, only: [:index]

  namespace :admin do

    root to: 'listings#index'

    resources :listings, except: [:show]

    resources :posts, except: [:show]

    resources :pages, except: [:show]

    resources :testimonials, except: [:show]

    resources :vendors, except: [:show]

    resources :dynamic_contents, except: [:show]
  end

end

app/views/shared/_admin_header.haml
%header#admin-header
  .row
    .large-10.large-centered.columns
      %h1 Administration
      %ul#nav
        %li= link_to 'Listings', admin_listings_path, class: @section == 'listings' ? 'active' : ''
        %li= link_to 'Posts', admin_posts_path, class: @section == 'posts' ? 'active' : ''
        %li= link_to 'Testimonials', admin_testimonials_path, class: @section == 'testimonials' ? 'active' : ''
        %li= link_to 'Content', admin_dynamic_contents_path, class: @section == 'dynamic_contents' ? 'active' : ''
        %li= link_to 'Pages', admin_pages_path, class: @section == 'pages' ? 'active' : ''
        %li= link_to 'Vendors', admin_vendors_path, class: @section == 'vendors' ? 'active' : ''
        %li= link_to 'Sign Out', destroy_admin_session_path, method: :delete

app/views/shared/_contact_modal.haml
.row#contact-modal.reveal-modal
  .large-12.columns
    %section
      %header
        %h4 Contact Me
        %a.close-reveal-modal &#215;

      .row
        .large-6.columns
          %p.strong.margin-bottom-0 2044 John Rolfe Parkway<br />Richmond, VA 23238
        .large-6.columns
          %p.strong.margin-bottom-0.text-right 804-921-7406

      %hr.full-bleed

      = form_for (@inquiry = Inquiry.new), html: { data: { abide: true }} do |f|
        = f.hidden_field :inquiry_type, value: 'contact'
        .row
          .large-4.columns
            = f.label :name, 'Name'
            = f.text_field :name, required: true
          .large-4.columns
            = f.label :email, 'Email'
            = f.text_field :email, required: true
          .large-4.columns
            = f.label :phone, 'Phone'
            = f.text_field :phone, required: true

        .row
          .large-12.columns
            = f.label :comments, 'Comments'
            = f.text_area :comments, required: true, class: 'margin-bottom-0'
            %small.error

        %footer
          .row
            .large-8.columns
              = f.label :humanizer_answer, @inquiry.humanizer_question
              = f.text_field :humanizer_answer
              = f.hidden_field :humanizer_question_id

            .large-4.columns.clearfix
              = f.submit 'Send!', class: 'button success right margin-bottom-0'

app/views/shared/_flashes.haml
- flash.each do |key, val|
  %p.flash{class: key}
    = val
    = link_to '', '#', class: 'icon-close'

app/views/shared/_global_footer.haml
%footer#global-footer
  .row
    .large-6.columns
      = regions_nav
    .large-6.columns
      %p
        %span.copyright Copyright &copy; 2013 - Daniel Keeton
        %span.dash &mdash;
        %span.images
          = link_to 'http://neumanndunn.com' do
            = image_tag 'neumann_and_dunn_logo_white.png', class: 'neumann-and-dunn'
          &mdash;
          = image_tag "realtor_logo.png"
          = image_tag "equal_housing.png"

app/views/shared/_global_header.haml
%header#global-header
  .row.hide-for-small
    .large-12.columns.clearfix
      %h1
        = link_to root_path do
          Daniel
          %span Keeton
      -#%ul#nav
        %li= link_to 'Home', root_path, class: @section == 'home' ? 'active' : ''
        %li= link_to 'Search MLS', listings_path, class: @section == 'listings' ? 'active' : ''
        %li= link_to 'Blog', posts_path, class: @section == 'posts' ? 'active' : ''
        %li= link_to 'Testimonials', testimonials_path, class: @section == 'testimonials' ? 'active' : ''
        %li= link_to 'Contact', '#', data: { :"reveal-id" => "contact-modal" }
      %ul#nav
        %li= link_to 'Home', root_path, class: @section == 'home' ? 'active' : ''
        %li= link_to 'Search Properties', listings_path, class: @section == 'listings' ? 'active' : ''
        %li= link_to 'Testimonials', testimonials_path, class: @section == 'testimonials' ? 'active' : ''
        %li.has-subnav
          = link_to 'Help', selling_index_path, class: @section == 'selling' ? 'active' : ''
          %ul.subnav
            %li= link_to 'Selling', selling_index_path, class: @section == 'selling' ? 'active' : ''
            %li= link_to 'Community', page_path(:id => 'community-resource'), class: @section == 'pages-community-resource' ? 'active' : ''
            %li= link_to 'Vendors', vendors_path, class: @section == 'vendors' ? 'active' : ''
        %li.has-subnav
          = link_to 'About', page_path(:id => 'about-me'), class: @section == 'pages-about-me' ? 'active' : ''
          %ul.subnav
            %li= link_to 'About Me', page_path(:id => 'about-me'), class: @section == 'pages-about-me' ? 'active' : ''
            %li= link_to 'Blog', posts_path, class: @section == 'posts' ? 'active' : ''
        %li= link_to 'Contact', '#', data: { :"reveal-id" => "contact-modal" }
      = link_to "What's my home worth?", '#', class: 'button success home-worth right', data: { :"reveal-id" => "home-worth-modal" }
  .row.show-for-small.hide-for-medium-up
    .large-4.columns.large-centered
      %h1.text-center
        Daniel
        %span Keeton
:javascript
  jQuery(document).ready(function($){
    $('#subnav li a.active').parents('#subnav').addClass('active');
  });

app/views/shared/_home_worth_modal.haml
.row#home-worth-modal.reveal-modal
  .large-12.colums
    %section
      %header
        %h4 What's my home worth?
        %a.close-reveal-modal &#215;

      %p.margin-bottom-0.mute Fill out this short online form to see how the recent real estate market has affected property values.

      %hr.full-bleed

      = form_for (@inquiry = Inquiry.new), html: { data: { abide: true }} do |f|
        = f.hidden_field :inquiry_type, value: 'homeworth'
        .row
          .large-4.columns
            = f.label :name, 'Name'
            = f.text_field :name, required: true
          .large-4.columns
            = f.label :email, 'Email'
            = f.text_field :email, required: true
          .large-4.columns
            = f.label :phone, 'Phone'
            = f.text_field :phone, required: true

        .row
          .large-12.columns
            = f.label :address, 'Home Address'
            = f.text_field :address, required: true

        .row
          .large-4.columns
            = f.label :square_footage, 'Square Footage'
            = f.text_field :square_footage, required: true
          .large-4.columns
            = f.label :bathrooms, '# Bathrooms'
            = f.text_field :bathrooms, required: true
          .large-4.columns
            = f.label :bedrooms, '# Bedrooms'
            = f.text_field :bedrooms, required: true

        .row
          .large-12.columns
            = f.label :updates, 'Updates'
            = f.text_area :updates, class: 'margin-bottom-0'

        %footer
          .row
            .large-8.columns
              = f.label :humanizer_answer, @inquiry.humanizer_question
              = f.text_field :humanizer_answer
              = f.hidden_field :humanizer_question_id

            .large-4.columns.clearfix
              = f.submit 'Get a Quote!', class: 'button success right margin-bottom-0'

app/views/shared/_mobile_navigation.haml
.row.show-for-small.hide-for-medium-up
  .small-12.columns
    -#%ul#mobile-nav
      .row
        .small-6.columns
          %li.nav-item= link_to 'Home', root_path, class: @section == 'home' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Search Properties', listings_path, class: @section == 'listings' ? 'active' : ''
      .row
        .small-6.columns
          %li.nav-item= link_to 'Blog', posts_path, class: @section == 'posts' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Testimonials', testimonials_path, class: @section == 'testimonials' ? 'active' : ''
      .row
        .small-6.columns
          %li.nav-item= link_to 'Contact', '#', data: { :"reveal-id" => "contact-modal" }
        .small-6.columns.hidden
          %li.nav-item= link_to 'Vendors', vendors_path, class: @section == 'vendors' ? 'active' : ''
      .row
        .small-6.columns.hidden
          %li.nav-item= link_to 'Selling', selling_index_path, class: @section == 'selling' ? 'active' : ''
        .small-6.columns.hidden
          %li.nav-item= link_to 'Community', page_path(:id => 'community-resource'), class: @section == 'pages-community-resource' ? 'active' : ''
      .row
        .small-12.columns.hidden
          %li.nav-item= link_to 'About', page_path(:id => 'about-me'), class: @section == 'pages-about-me' ? 'active' : ''

      .row
        .small-12.columns
          %li.action-item= link_to "What's My Home Worth?", '#', class: 'button success home-worth', data: { :"reveal-id" => "home-worth-modal" }

    %ul#mobile-nav
      .row
        .small-6.columns
          %li.nav-item= link_to 'Home', root_path, class: @section == 'home' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Search Properties', listings_path, class: @section == 'listings' ? 'active' : ''
      .row
        .small-6.columns
          %li.nav-item= link_to 'Testimonials', testimonials_path, class: @section == 'testimonials' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Selling', selling_index_path, class: @section == 'selling' ? 'active' : ''
      .row
        .small-6.columns
          %li.nav-item= link_to 'Community', page_path(:id => 'community-resource'), class: @section == 'pages-community-resource' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Vendors', vendors_path, class: @section == 'vendors' ? 'active' : ''
      .row
        .small-6.columns
          %li.nav-item= link_to 'About Me', page_path(:id => 'about-me'), class: @section == 'pages-about-me' ? 'active' : ''
        .small-6.columns
          %li.nav-item= link_to 'Blog', posts_path, class: @section == 'posts' ? 'active' : ''
      .row
        .small-12.columns
          %li.nav-item= link_to 'Contact', '#', data: { :"reveal-id" => "contact-modal" }

      .row
        .small-12.columns
          %li.action-item= link_to "What's My Home Worth?", '#', class: 'button success home-worth', data: { :"reveal-id" => "home-worth-modal" }

app/views/shared/_orbit_module.haml
.row
  .large-12.columns
    %ul{data: { orbit: true }}
      %li
        = image_tag 'richmond/shortpump.jpg'
        .orbit-caption
          Richmond is home to over 900 restaurants and incredibly diverse
          shopping, including the beautiful outdoor Short Pump Town Center.
      %li
        = image_tag 'richmond/vcu.jpg'
        .orbit-caption
          In the Richmond area you will find some of the nations top schools,
          from elementary education to top colleges like Virginia Commonwealth
          University and the University of Richmond. Even in the rural areas of
          Goochland, Chesterfield or Hanover you're never more than a short
          drive from world class shopping, dining and entertainment.
      %li
        = image_tag 'richmond/uva-rotunda.jpg'
        .orbit-caption
          Only a 45 minute drive west will bring you to Charlottesville, a small
          town unlike any other. C-ville is known nationally as melting pot of
          art, culture and entertainment all mixed in to a small town feel.
      %li
        = image_tag 'richmond/neptune.jpg'
        .orbit-caption
          If you love the ocean, simply take a short drive East and you're at
          Virginias beautiful coastline with some of the best beaches on the
          East coast.

app/views/shared/_slider.haml
- if images.any?
  .row
    .large-12.columns
      .slideshow-wrapper
        .preloader
        %ul{data: { orbit: true }}
          - images.each do |image|
            %li
              = image_tag image.image
              = slider_caption(image)