config/routes.rb
DanielkeetonCom::Application.routes.draw do

  root to: 'home#index'

  devise_for :admins, skip: :registrations

  resources :listings, only: [:show] do
    collection do
      get '/', to: 'listings#index', defaults: { status: 'for_sale' }
      get 'status/:status', to: 'listings#index', as: :status
    end
  end

  get '/homeworth', to: 'home#homeworth'

  resources :posts, only: [:index, :show]
  resources :inquiries, only: [:create]
  resources :pages, only: [:show]
  resources :testimonials, only: [:index]
  resources :vendors, only: [:index]
  resources :selling, only: [:index]

  namespace :admin do

    root to: 'listings#index'

    resources :listings, except: [:show]

    resources :posts, except: [:show]

    resources :pages, except: [:show]

    resources :testimonials, except: [:show]

    resources :vendors, except: [:show]

    resources :dynamic_contents, except: [:show]
  end

end

app/models/vendor.rb
# Public: The Vendor class handles all vendors in the website.
# This includes everything in VALID_SUBJECTS.
class Vendor < ActiveRecord::Base

  # Internal: Use CarrierWave to mount the VendorUploader on :image.
  mount_uploader :image, VendorUploader

  # Internal: Validate presence of specified attributes.
  validates :label, presence: true

end

app/controllers/admin/vendors_controller.rb
class Admin::VendorsController < Admin::BaseController

  # Internal: A testable class for use with strong_parameters.
  class VendorParams

    # Internal: Build params for creating/updating a Vendor.
    #
    # Examples
    #
    #   VendorParams.build(vendor: { subject: 'biography' })
    #   # => { 'subject' => 'biography' }
    def self.build(params)
      params.require(:vendor).permit!
    end
  end

  def index
    @vendors = Vendor.all
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update_attributes(VendorParams.build(params))
      redirect_to admin_vendors_path, notice: 'Vendor successfully updated!'
    else
      flash.now[:error] = 'Oops! There was a problem updating the vendor.'
      render :edit
    end
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(VendorParams.build(params))
    if @vendor.save
      redirect_to admin_vendors_path, notice: 'Vendor successfully created!'
    else
      flash.now[:error] = 'Oops! There was a problem creating the vendor.'
      render :new
    end
  end

  def destroy
    if Vendor.find(params[:id]).destroy
      flash[:notice] = 'Vendor successfully deleted!'
    else
      flash[:error] = 'Oops! There was a problem deleting the vendor.'
    end

    redirect_to admin_vendors_path
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @vendors = Vendor.all
  end

end

app/views/admin/vendors/_form.haml
= form_for [:admin, vendor], html: { class: 'custom vendors-form' } do |f|
  .row
    .large-12.columns
      = f.label :label, 'Label'
      = f.text_field :label

  .row
    .large-12.columns
      = f.label :link, 'Link'
      = f.text_field :link

  .row
    .large-12.columns
      = f.label :image
      = f.file_field :image
      - unless f.object.image.blank?
        = image_tag f.object.image.thumb

  %footer
    .row
      .large-6.columns
        = link_to 'Cancel', admin_vendors_path, class: 'button secondary'
      .large-6.columns.text-right
        = f.submit 'Save', class: 'button success'

app/views/admin/vendors/_vendors.haml
- vendors_header ||= 'Vendors'
- include_new = true if include_new.nil?

%h4
  = vendors_header
  - if include_new
    %span
      = link_to 'New', new_admin_vendor_path, class: 'button tiny'

%section
  %ul.admin-list
    - vendors.each do |vendor|
      %li.row
        .large-10.columns
          = vendor.label
        .large-2.columns
          %ul.actions
            %li= link_to '', edit_admin_vendor_path(vendor), class: 'icon-edit'
            %li= link_to '', admin_vendor_path(vendor), method: :delete, confirm: 'Are you sure?', class: 'icon-delete'

app/views/admin/vendors/edit.haml
%h4 Edit Vendor
%section
  = render 'form', vendor: @vendor

app/views/admin/vendors/index.haml
= render 'vendors', vendors: @vendors

app/views/admin/vendors/new.haml
%h4 New Vendor
%section
  = render 'form', vendor: @vendor